### ISSUE TITLE
Installation..problem with GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by sshman3** [mathLab/PyGeM#170]
Hello,
I try to install PyGem..with following this steps on CentOS7:

1) install conda
2) conda create --name gempy36 python=3.6
3) conda activate gempy36
4) conda install -c conda-forge -c dlr-sc -c pythonocc -c oce pythonocc-core==0.17 python=3.6
5) python -m pip install alla packages ( numpy, scipy, matplotlib, vtk, numpy-stl, sphinx and nose) 
6) python test.py

### !! Error..with :

ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/_BRep.so)

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named '_BRep')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/_BRep.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gghe/Py/PyGeM/tests/test_stlhandler.py", line 3, in <module>
    import pygem.stlhandler as sh
  File "/home/gghe/Py/PyGeM/pygem/__init__.py", line 19, in <module>
    from .nurbshandler import NurbsHandler
  File "/home/gghe/Py/PyGeM/pygem/nurbshandler.py", line 9, in <module>
    from OCC.BRep import BRep_Tool, BRep_Builder, BRep_Tool_Curve
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 21, in <module>
    _BRep = swig_import_helper()
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 20, in swig_import_helper
    return importlib.import_module('_BRep')
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_BRep'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named '_BRep')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/_BRep.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gghe/Py/PyGeM/tests/test_unvhandler.py", line 3, in <module>
    import pygem.unvhandler as uh
  File "/home/gghe/Py/PyGeM/pygem/__init__.py", line 19, in <module>
    from .nurbshandler import NurbsHandler
  File "/home/gghe/Py/PyGeM/pygem/nurbshandler.py", line 9, in <module>
    from OCC.BRep import BRep_Tool, BRep_Builder, BRep_Tool_Curve
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 21, in <module>
    _BRep = swig_import_helper()
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 20, in swig_import_helper
    return importlib.import_module('_BRep')
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_BRep'

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named '_BRep')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/_BRep.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gghe/Py/PyGeM/tests/test_vtkhandler.py", line 3, in <module>
    import pygem.vtkhandler as vh
  File "/home/gghe/Py/PyGeM/pygem/__init__.py", line 19, in <module>
    from .nurbshandler import NurbsHandler
  File "/home/gghe/Py/PyGeM/pygem/nurbshandler.py", line 9, in <module>
    from OCC.BRep import BRep_Tool, BRep_Builder, BRep_Tool_Curve
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 21, in <module>
    _BRep = swig_import_helper()
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/site-packages/OCC/BRep.py", line 20, in swig_import_helper
    return importlib.import_module('_BRep')
  File "/home/gghe/.conda/envs/gempy36/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_BRep'

----------------------------------------------------------------------
Ran 28 tests in 0.099s

FAILED (errors=28)

any suggestions..please?

Cheers,
David

**Comment by mtezzele** [comment]
Hi @sshman3, 
sorry for the late response. I suggest you to install all the dependencies with conda. This way it will automatically find all the compatible versions. Let us know if this helps.
