### ISSUE TITLE
Installation problem with Dockerfile

### ISSUE THREAD

**Issue by matsubaraDaisuke** [mathLab/PyGeM#175]
Hi I'm matsubara

I Tried to build PyGeM with Dockerfile(Docker-compose)

But I failed the last Stage

``` Dockerfile
RUN cd $HOME  && \
    cd build && \
    git clone https://github.com/mathLab/PyGeM.git   && \
    cd PyGeM && \
    python setup.py install
```

The error message is below 

``` Dockerfile
Running Pygments-2.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ng2UJ4/Pygments-2.6.1/egg-dist-tmp-QnN2Vh
  File "build/bdist.linux-x86_64/egg/pygments/lexer.py", line 49
    class Lexer(metaclass=LexerMeta):
                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pygments/formatters/html.py", line 554
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pygments/style.py", line 171
    class Style(metaclass=StyleMeta):
                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/pygments/cmdline.py", line 161
    print("%s not found!" % what, file=sys.stderr)
                                      ^
SyntaxError: invalid syntax

creating /usr/local/miniconda/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg
Extracting Pygments-2.6.1-py2.7.egg to /usr/local/miniconda/lib/python2.7/site-packages
  File "/usr/local/miniconda/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/cmdline.py", line 161
    print("%s not found!" % what, file=sys.stderr)
                                      ^
SyntaxError: invalid syntax

  File "/usr/local/miniconda/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/lexer.py", line 49
    class Lexer(metaclass=LexerMeta):
                         ^
SyntaxError: invalid syntax

  File "/usr/local/miniconda/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/style.py", line 171
    class Style(metaclass=StyleMeta):
                         ^
SyntaxError: invalid syntax

  File "/usr/local/miniconda/lib/python2.7/site-packages/Pygments-2.6.1-py2.7.egg/pygments/formatters/html.py", line 554
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

******

Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    zip_safe=False)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/miniconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/local/miniconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/miniconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/usr/local/miniconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/local/miniconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/miniconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-2ZicmT/Jinja2-3.0.0a1/setup.py", line 6, in <module>
    This function just return the content of README.md
  File "/usr/local/miniconda/lib/python2.7/site-packages/setuptools/sandbox.py", line 419, in _open
    return _open(path, mode, *args, **kw)
TypeError: 'encoding' is an invalid keyword argument for this function
```

Please check the Dockerfile
Thank you.

**Comment by mtezzele** [comment]
Dear @matsubaraDaisuke unfortunately the docker support was an external contribution. We do not maintain it anymore. I suggest you to follow the other installation methods. Moreover in the near future we will migrate to py3.
